apiVersion: apps/v1
kind: Deployment
metadata:
  name: comentarios-api
  labels:
    app: comentarios
spec:
  replicas: 4
  selector:
    matchLabels:
      app: comentarios
  template:
    metadata:
      labels:
        app: comentarios
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup
                    operator: In
                    values:
                      - api-nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - comentarios
              topologyKey: kubernetes.io/hostname
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: comentarios-api
          image: comentarios-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/status
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10